### ISSUE TITLE
Error while adding Catalog item

### ISSUE THREAD

**Issue by akshaygin** [enhance-manageiq/project-setup#3]
Following [this](http://www.tigeriq.co/openstack-ansible-inside/) guide to run Ansible playbook inside ManageIQ. We have completed adding Service dialogue and then also created service catalog. But while adding a Service Catalog item, throws this error:
![screenshot from 2018-01-17 13-24-50](https://user-images.githubusercontent.com/16691314/35031642-c055c782-fb5b-11e7-8f56-62a65411e030.png)

Error appears in evm.log is:
```
[----] E, [2018-01-17T13:26:11.478066 #3191:7f0b9d0] ERROR -- : MIQ(ManageIQ::Providers::Openstack::CloudManager::EventCatcher::Runner#start_event_mon
itor) EMS [172.22.26.201] as [admin] Event Monitor Thread aborted because [Expected(200) <=> Actual(404 Not Found)
excon.error.response
  :body          => "{\"error_message\": {\"code\": 404, \"description\": \"\", \"title\": \"Not Found\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Connection"             => "close"
    "Content-Length"         => "73"
    "Content-Type"           => "application/json"
    "Date"                   => "Wed, 17 Jan 2018 07:56:11 GMT"
    "Server"                 => "Apache/2.4.6 (CentOS)"
    "x-openstack-request-id" => "req-59a86503-2218-4aa6-aa97-04985a0e5d5c"
  }
  :host          => "172.22.26.201"
  :local_address => "192.168.122.161"
  :local_port    => 59142
  :path          => "/v2/events"
  :port          => 8777
  :reason_phrase => "Not Found"
  :remote_ip     => "172.22.26.201"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"
]
[----] E, [2018-01-17T13:26:11.478188 #3191:7f0b9d0] ERROR -- : [Fog::Metering::OpenStack::NotFound]: Expected(200) <=> Actual(404 Not Found)
excon.error.response
  :body          => "{\"error_message\": {\"code\": 404, \"description\": \"\", \"title\": \"Not Found\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Connection"             => "close"
    "Content-Length"         => "73"
    "Content-Type"           => "application/json"
    "Date"                   => "Wed, 17 Jan 2018 07:56:11 GMT"
    "Server"                 => "Apache/2.4.6 (CentOS)"
    "x-openstack-request-id" => "req-59a86503-2218-4aa6-aa97-04985a0e5d5c"
  }
  :host          => "172.22.26.201"
  :local_address => "192.168.122.161"
  :local_port    => 59142
  :path          => "/v2/events"
  :port          => 8777
  :reason_phrase => "Not Found"
  :remote_ip     => "172.22.26.201"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"
  Method:[block in method_missing]
[----] E, [2018-01-17T13:26:11.478230 #3191:7f0b9d0] ERROR -- : /usr/local/lib/ruby/gems/2.3.0/gems/excon-0.59.0/lib/excon/middlewares/expects.rb:7:in `response_call'
/usr/local/lib/ruby/gems/2.3.0/gems/excon-0.59.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
/usr/local/lib/ruby/gems/2.3.0/gems/docker-api-1.33.6/lib/excon/middlewares/hijack.rb:45:in `response_call'
/usr/local/lib/ruby/gems/2.3.0/gems/excon-0.59.0/lib/excon/connection.rb:389:in `response'
/usr/local/lib/ruby/gems/2.3.0/gems/excon-0.59.0/lib/excon/connection.rb:253:in `request'
/usr/local/lib/ruby/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/connection.rb:81:in `request'
/usr/local/lib/ruby/gems/2.3.0/gems/fog-openstack-0.1.22/lib/fog/openstack/core.rb:81:in `request'
/usr/local/lib/ruby/gems/2.3.0/gems/fog-openstack-0.1.22/lib/fog/metering/openstack/requests/list_events.rb:20:in `list_events'
/usr/local/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
/usr/local/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-openstack-88cd066db20e/lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb:102:in `list_events'
/usr/local/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-openstack-88cd066db20e/lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb:49:in `each_batch'
/usr/local/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-openstack-88cd066db20e/app/models/manageiq/providers/openstack/event_catcher_mixin.rb:39:in `monitor_events'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/event_catcher/runner.rb:161:in `block in start_event_monitor'
```
Expected Output:
Service Catalog item should add.

**Comment by akshaygin** [comment]
When I am tracking this error, I found that it because of *ceilometer-api* service in OpenStack which is not running. It failed to start because of this error `Address already in use`
Full error log from `/var/log/ceilometer/api.log`:

```
2018-01-18 18:23:41.814 28286 INFO ceilometer.storage.mongo.utils [-] Connecting to mongodb on [('172.22.26.201', 27017)]
2018-01-18 18:23:41.837 28286 WARNING keystonemiddleware.auth_token [-] AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
2018-01-18 18:23:41.850 28286 CRITICAL ceilometer [-] error: [Errno 98] Address already in use
2018-01-18 18:23:41.850 28286 ERROR ceilometer Traceback (most recent call last):
2018-01-18 18:23:41.850 28286 ERROR ceilometer   File "/usr/bin/ceilometer-api", line 34, in <module>
2018-01-18 18:23:41.850 28286 ERROR ceilometer     server = wss.make_server('', args.port, build_wsgi_app())
2018-01-18 18:23:41.850 28286 ERROR ceilometer   File "/usr/lib64/python2.7/wsgiref/simple_server.py", line 144, in make_server
2018-01-18 18:23:41.850 28286 ERROR ceilometer     server = server_class((host, port), handler_class)
2018-01-18 18:23:41.850 28286 ERROR ceilometer   File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
2018-01-18 18:23:41.850 28286 ERROR ceilometer     self.server_bind()
2018-01-18 18:23:41.850 28286 ERROR ceilometer   File "/usr/lib64/python2.7/wsgiref/simple_server.py", line 48, in server_bind
2018-01-18 18:23:41.850 28286 ERROR ceilometer     HTTPServer.server_bind(self)
2018-01-18 18:23:41.850 28286 ERROR ceilometer   File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
2018-01-18 18:23:41.850 28286 ERROR ceilometer     SocketServer.TCPServer.server_bind(self)
2018-01-18 18:23:41.850 28286 ERROR ceilometer   File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
2018-01-18 18:23:41.850 28286 ERROR ceilometer     self.socket.bind(self.server_address)
2018-01-18 18:23:41.850 28286 ERROR ceilometer   File "/usr/lib64/python2.7/socket.py", line 224, in meth
2018-01-18 18:23:41.850 28286 ERROR ceilometer     return getattr(self._sock,name)(*args)
2018-01-18 18:23:41.850 28286 ERROR ceilometer error: [Errno 98] Address already in use
2018-01-18 18:23:41.850 28286 ERROR ceilometer 
```

**Comment by akshaygin** [comment]
It turned out system had reserved `8777` ports in `/etc/httpd/conf/ports.conf` for httpd which was causing _ceilometer-api_ service to fail because it couldn't bind to port 8777.

Commenting port 8777 in `/etc/httpd/conf/ports.conf` and restarting httpd and ceilometer service, it seemed ceilometer work again. But ManageIQ error still exists.

**Comment by KhushbuB** [comment]
The [Panko](https://docs.openstack.org/panko/latest/) project is an event storage service that provides the ability to store and querying event data generated by Ceilometer with potentially other sources. Panko was not installed and we got to know this as we ran throw the answer file of packstack. Panko is installed successfully using answer file.

**Comment by akshaygin** [comment]
Installation of `panko` service solved this issue.
